name: Notify on Discord
on: push
jobs:
  build:
    name: Actions for Discord
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}